name: Documentation
description: File an issue against the <a href="https://developer.grammarly.com/">public documentation</a>.
title: "[Docs]: "
labels: ["docs"]
assignees:
  - AndrewDiMola
body:
  - type: input
    id: source
    attributes:
      label: Documentation URL
      description: Please provide the link to the documentation page.
    validations:
      required: false
  - type: textarea
    id: happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expect
    attributes:
      label: What did you expect to happen?
      placeholder: Tell us what you want!
    validations:
      required: true
        ---
  - type: markdown
    attributes:
      value: "__Thanks for completing our form!__"
