on:
  issues:
    types: [opened]

name: Jira Actions

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Login
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: ${{ secrets.JIRA_PROJECT }}
        issuetype: ${{ secrets.JIRA_TYPE }}
        summary: |
            ${{ github.event.issue.title }}
        description: |
            ${{ github.event.issue.body }}
            ----
            {panel}
            _[Github permalink |${{ github.event.issue.html_url }}]_
            {panel}
        fields: '{"labels": ["${{ secrets.JIRA_LABEL }}"] }'
